# set up cache to speed up builds
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .cargo/
    - .cache/sccache

stages:
  - test
  - build
  - docker
  - deploy

# make sure that formatting is correct.
rustfmt:
  image: registry.gitlab.com/fractalnetworks/images/rust:stable
  stage: test
  allow_failure: true
  script:
    - ci-setup-cargo
    - cargo fmt -- --check
  interruptible: true

# make sure there are no issues with the code.
clippy:
  image: registry.gitlab.com/fractalnetworks/images/rust:stable
  stage: test
  allow_failure: true
  script:
    - ci-setup-cargo
    - cargo clippy
  interruptible: true

# run unit tests.
test:
  image: registry.gitlab.com/fractalnetworks/images/rust:stable
  stage: test
  script:
    - ci-setup-cargo
    - cargo test
  interruptible: true

# generate release build
build:amd64:
  image: registry.gitlab.com/fractalnetworks/images/rust:stable
  stage: build
  script:
    - ci-setup-cargo
    - cargo build --release
  artifacts:
    paths:
      - target/release/gateway
    expire_in: 1 week
  interruptible: true

# build for arm target
build:arm32:
  image: registry.gitlab.com/fractalnetworks/images/rust:stable-arm32
  stage: build
  script:
    - ci-setup-cargo
    - cargo build --release --target arm-unknown-linux-gnueabihf
  artifacts:
    paths:
      - target/arm-unknown-linux-gnueabihf/release/gateway
    expire_in: 1 week
  interruptible: true

# build for arm target
build:arm64:
  image: registry.gitlab.com/fractalnetworks/images/rust:stable-arm64
  stage: build
  script:
    - ci-setup-cargo
    - cargo build --release --target aarch64-unknown-linux-gnu
  artifacts:
    paths:
      - target/aarch64-unknown-linux-gnu/release/gateway
    expire_in: 1 week
  interruptible: true

# generate swagger API docs.
openapi:
  allow_failure: true
  stage: build
  image: registry.gitlab.com/fractalnetworks/images/rust:stable-amd64
  script:
    - cargo build --features openapi
    - mkdir -p target/openapi
    - target/debug/gateway --secret abc --openapi > target/openapi/openapi.json
  artifacts:
    paths:
      - target/openapi
    expire_in: 1 week
  interruptible: true

# generate rust html documentation
rustdoc:
  image: registry.gitlab.com/fractalnetworks/images/rust:stable
  stage: build
  script:
    - ci-setup-cargo
    - cargo doc
  artifacts:
    paths:
      - target/doc
    expire_in: 1 week
  interruptible: true

docker:
  dependencies:
    - build:amd64
  image: docker
  stage: docker
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build . -t "$CI_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY_IMAGE:latest"
  only:
    - master

# publish binary, docs and API docs to gitlab pages.
pages:
  image: registry.gitlab.com/fractalnetworks/images/pages
  stage: deploy
  dependencies:
    - build:amd64
    - build:arm32
    - build:arm64
    - openapi
    - rustdoc
  script:
    - mkdir public
    - mv target/doc public/doc
    - mv target/openapi public/openapi
    - mv target/release/gateway public/gateway-master-amd64
    - sign public/gateway-master-amd64
    - mv target/arm-unknown-linux-gnueabihf/release/gateway public/gateway-master-arm32
    - sign public/gateway-master-arm32
    - mv target/aarch64-unknown-linux-gnu/release/gateway public/gateway-master-arm64
    - sign public/gateway-master-arm64
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - master
