image: rustlang/rust:nightly

# set up cache to speed up builds
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .cargo/
    - .cache/sccache

before_script:
  - wget https://github.com/mozilla/sccache/releases/download/v0.2.15/sccache-v0.2.15-x86_64-unknown-linux-musl.tar.gz -O /tmp/sccache.tar.gz
  - tar -xf /tmp/sccache.tar.gz --strip-components=1 -C /usr/local/bin/
  - chmod +x /usr/local/bin/sccache
  - export CARGO_HOME="${PWD}/.cargo"
  - export SCCACHE_DIR="${PWD}/.cache/sccache"
  - export RUSTC_WRAPPER="/usr/local/bin/sccache"

stages:
  - test
  - build
  - deploy

# make sure that formatting is correct.
rustfmt:
  stage: test
  allow_failure: true
  script:
    - cargo fmt -- --check

# make sure there are no issues with the code.
clippy:
  stage: test
  allow_failure: true
  script:
    - cargo clippy

# run unit tests.
test:
  stage: test
  script:
    - cargo test

# generate release build
build:
  stage: build
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/gateway
    expire_in: 1 week

# generate swagger API docs.
api:
  stage: deploy
  image: node:10-alpine
  before_script:
    - npm install swagger-ui-dist@3.22.1
    - npm install yaml-to-json -g
  script:
    - mkdir swagger
    - cp -rp node_modules/swagger-ui-dist/* swagger
    - yaml2json api --output swagger
    - sed -i "s#https://petstore\.swagger\.io/v2/swagger\.json#gateway_0.1.0.json#g" public/index.html
  artifacts:
    paths:
      - swagger

# publish binary, docs and API docs to gitlab pages.
pages:
  stage: deploy
  dependencies:
    - build
    - api
  script:
    - cargo doc
    - mv target/doc public
    - mv target/release/gateway public/gateway-master-amd64
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - master
