image: rustlang/rust:nightly

stages:
  - test
  - build
  - deploy

rustfmt:
  stage: test
  allow_failure: true
  script:
    - cargo fmt -- --check

clippy:
  stage: test
  allow_failure: true
  script:
    - cargo clippy

test:
  stage: test
  script:
    - cargo test

build:
  stage: build
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/gateway
    expire_in: 1 week

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - cargo doc
    - mv target/doc public
    - mv target/release/gateway public/gateway-master-amd64
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - master
