[package]
name = "gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["json"] }
tokio = { version = "1.3.0", features = ["process"] }
serde = { version = "1.0.124", features = ["derive"] }
anyhow = "1.0.38"
base64 = "0.13.0"
rand_core = "0.6.2"
x25519-dalek-fiat = "0.1.0"
thiserror = "1.0.24"
ipnet = "2.3.0"
serde_with = "1.6.4"
serde_json = "1.0.64"
sqlx = { version = "0.5.1", features = ["sqlite", "runtime-tokio-native-tls"] }
structopt = "0.3.21"
env_logger = "0.8.3"
log = "0.4.14"
itertools = "0.10.0"
parse_duration = "2.1.0"
lazy_static = "1.4.0"
tera = "1.7.0"
futures = "0.3.13"
url = { version = "2", features = ["serde"] }
base32 = "0.4.0"
