[package]
name = "gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["json"] }
tokio = { version = "1", features = ["process"] }
serde = { version = "1", features = ["derive"] }
anyhow = "1.0"
base64 = "0.13"
rand_core = "0.6"
x25519-dalek-fiat = "0.1.0"
thiserror = "1.0"
ipnet = "2.3.0"
serde_with = "1.6.4"
serde_json = "1.0"
sqlx = { version = "0.5.1", features = ["sqlite", "runtime-tokio-native-tls"] }
structopt = "0.3"
env_logger = "0.8"
log = "0.4"
itertools = "0.10.0"
parse_duration = "2.1.0"
lazy_static = "1.4.0"
