[package]
name = "gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.17.0", features = ["process", "sync", "macros", "rt-multi-thread"] }
serde = { version = "1.0.136", features = ["derive"] }
anyhow = "1.0.55"
rand_core = "0.6.3"
thiserror = "1.0.30"
ipnet = "2.3.1"
serde_json = "1.0.79"
sqlx = { version = "0.5.11", features = ["sqlite", "runtime-tokio-rustls"] }
structopt = "0.3.26"
env_logger = "0.9.0"
log = "0.4.14"
itertools = "0.10.3"
parse_duration = "2.1.1"
lazy_static = "1.4.0"
tera = "1.15.0"
futures = "0.3.21"
url = { version = "2.2.2", features = ["serde"] }
gateway-client = { git = "https://gitlab.com/fractalnetworks/gateway-client", branch = "v0.1" }
gateway-manager-client = { git = "https://gitlab.com/fractalnetworks/gateway-manager-client", branch = "v0.1" }
wireguard-keys = "0.1"
regex = "1.5.4"
tokio-stream = { version = "0.1.8", features = ["sync"] }
event-types = { git = "https://gitlab.com/fractalnetworks/event-types", features = ["broadcast"], branch = "v0.1" }
tokio-tungstenite = "0.17.1"
base32 = "0.4.0"
tokio-util = { version = "0.7.0", features = ["codec"] }
tokio-serde = "0.8.0"

[features]
default = []
