[package]
name = "gateway-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.38"
async-trait = "0.1.48"
ipnet = { version = "2.3.0", features = ["serde"] }
log = "0.4.14"
reqwest = { version = "0.11.2", default-features = false, features = ["rustls-tls", "json"], optional = true }
serde = { version = "1.0.124", features = ["derive"] }
serde_json = { version = "1.0.72", optional = true }
structopt = { version = "0.3.21", optional = true }
thiserror = "1.0.30"
tokio = { version = "1.3.0", optional = true }
url = { version = "2.2.1", features = ["serde"] }
wireguard-keys = { git = "https://gitlab.com/fractalnetworks/wireguard-keys" }
schemars = { git = "https://github.com/xfbs/schemars", features = ["ipnet"], optional = true }
tonic = { version = "0.6", optional = true }
prost = { version = "0.9", optional = true }
futures = "0.3.19"

[features]
default = ["proto"]
api = ["reqwest"]
schema = ["schemars", "wireguard-keys/schema"]
cli = ["api", "structopt", "tokio/rt", "tokio/macros", "tokio/io-std", "tokio/fs", "serde_json"]
proto = ["tonic", "prost"]

[dev-dependencies]
tokio = { version = "1.3.0", features = ["full"] }
mockito = "0.30.0"

[build-dependencies]
tonic-build = "0.6"

[[bin]]
name = "client"
required-features = ["cli"]
